// <auto-generated />
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026063939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.LtPayments", b =>
                {
                    b.Property<int>("Payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Payment_id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Payment_date")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Rental_id")
                        .HasColumnType("int");

                    b.HasKey("Payment_id");

                    b.ToTable("LtPayment");
                });

            modelBuilder.Entity("Database.Models.MsCar", b =>
                {
                    b.Property<int>("Car_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Car_id"));

                    b.Property<string>("License_Plate")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Number_of_car_seats")
                        .HasColumnType("int");

                    b.Property<int>("Price_per_day")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Car_id");

                    b.ToTable("Mscar");
                });

            modelBuilder.Entity("Database.Models.MsCarImages", b =>
                {
                    b.Property<int>("Image_Car_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Image_Car_Id"));

                    b.Property<int>("Car_id")
                        .HasColumnType("int");

                    b.Property<string>("Image_link")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Image_Car_Id");

                    b.ToTable("MsCarImages");
                });

            modelBuilder.Entity("Database.Models.MsCustomer", b =>
                {
                    b.Property<int>("Customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Customer_id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Driver_license_number")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Customer_id");

                    b.ToTable("MsCustomer");
                });

            modelBuilder.Entity("Database.Models.MsEmployee", b =>
                {
                    b.Property<int>("Employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Employee_id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Employee_id");

                    b.ToTable("MsEmployee");
                });

            modelBuilder.Entity("Database.Models.TrMaintenance", b =>
                {
                    b.Property<int>("Maintenance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Maintenance_id"));

                    b.Property<int>("Car_id")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Decription")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<string>("Maintenance_date")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.HasKey("Maintenance_id");

                    b.ToTable("TrMaintenance");
                });

            modelBuilder.Entity("Database.Models.TrRental", b =>
                {
                    b.Property<int>("Rental_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Rental_id"));

                    b.Property<int>("Car_id")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int");

                    b.Property<string>("Payment_status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Rental_Date")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Return_Date")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("Total_price")
                        .HasColumnType("int");

                    b.HasKey("Rental_id");

                    b.ToTable("TrRental");
                });
#pragma warning restore 612, 618
        }
    }
}
